### ISSUE TITLE
Is there a CPP which includes the main function for the exe file "calculateFDRs"?

### ISSUE THREAD

**Issue by Pandaman-Ryan** [mhk7/alignOntology#1]
Hi, 

Is there a CPP which includes the main function for the exe file "calculateFDRs"?
I hope to further understand how the FDR process works. :-) 

Thanks!!

**Comment by mhk7** [comment]
Hi Ryan,

Thanks for the question.  calculateFDRs is just a bash script, so there is
no cpp file associated with it - all the info about how it works is in
there.  A lot of the work of that script is done in
calculateFDRsForAlignment, which has a CPP file in the github repository.
If you'd like a more theoretical explanation of the FDR process, please see
the methods section here:
http://www.nature.com/nbt/journal/v31/n1/full/nbt.2463.html

Let me know if you have any other questions (or if this didn't answer your
original question)!

Mike
