### ISSUE TITLE
How exactly is the score (in column 3) calculated?

### ISSUE THREAD

**Issue by antonkratz** [mhk7/alignOntology#5]
How exactly is the score (in column 3) calculated?

I do not find an explanation in the documentation of this repo; I do find some explanation from the paper:

> 2.3.1 Ontology alignment
> "Term mapping in our alignment procedure is evaluated using a score function that considers the similarity of the sets of genes assigned to terms (intrinsic similarity) and the similarity of the ontology hierarchy surrounding each term (relational similarity). Each pair of terms which is aligned receives an alignment score ranging from 0 to 1 where 1 represents identity in both intrinsic and relational similarity."

Still, it is not clear how this score is calculated exactly - how does it consider the similarity etc?

**Comment by mhk7** [comment]
Hi Anton!

Thanks for the question. The method is described in some detail in the online methods of this paper in the Ontology alignment section. Let me know if it’s not clear with the more thorough written explanation. (Section starts with “Given two ontologies, O1 with n1 terms and O2with n2 terms, an ontology alignment A is a mapping of terms between ontologies...”).

Michael

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3654867/#!po=0.793651

**Comment by antonkratz** [comment]
Thank you Michael, there is indeed a very thorough explanation! I was somehow fixated on the idea that the explanation is in the "Inferring gene ontologies from pairwise similarity data" paper, didn't even consider looking in the "A gene ontology inferred from molecular networks" paper (where it is). This clarifies the score formula! Thanks and closing this issue.
